FORMAT: 1A

# node-restify-coffee-boilerplate

Boilerplate for APIs using Restify and CoffeeScript

Source code is available on [GitHub](https://github.com/gszathmari/node-restify-coffee-boilerplate)

# API Root [/]

This resource prints the standard "Hello Word!" message in a JSON format

## Retrieve "Hello World!" [GET]

+ Response 200 (application/json)

        {"message":"Hello World!"}
